apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: ai-incident-responder/agent:latest
          env:
            - name: GATEWAY_WS_URL
              value: "ws://api-server:3000/ws" 