apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-processor
  template:
    metadata:
      labels:
        app: ai-processor
    spec:
      containers:
        - name: ai-processor
          image: ai-incident-responder/services/ai-processor:latest
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: apiKey
            - name: FLUVIO_ADDR
              value: "fluvio:9003"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-processor
spec:
  selector:
    app: ai-processor
  ports:
    - port: 8000 