apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: ai-incident-responder/services/api-server:latest
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:password@postgres:5432/incidentdb"
            - name: JWT_SECRET
              value: "supersecretjwt"
            - name: FLUVIO_ADDR
              value: "fluvio:9003"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - port: 3000 